steps:
- name: 'docker-build'
    entrypoint: 'docker'
    args: ['build', '-t', 'gcr.io/clean-mountain-395906/nodejsimage-1', '.']

  - name: 'gcloud-deploy'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'nodejs-servertest', '--image', 'gcr.io/clean-mountain-395906/nodejsimage-1', '--region', 'us-central1']

images:
  - name: 'gcr.io/clean-mountain-395906/nodejsimage-1'

- gcr.io/clean-mountain-395906/IMAGE
    
 # steps:
 # - name: 'node'
 #   entrypoint: 'npm'
 #   args: ['install', '-g', 'snyk']
 # - name: 'node'
 #   args: ['snyk', 'auth', '$_SNYK_TOKEN']
    
 # - name: 'node'
 #   args: ['snyk', 'test']


            

  

