steps:
  
  
  - name: 'gcr.io/clean-mountain-395906/sonar-scanner'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=dc9b9bae3665ce05dc57001fff13ca3a0c26be5d'
    - '-Dsonar.projectKey=my-first-sacn_gcp'
    - '-Dsonar.organization=my-first-sacn'
    - '-Dsonar.sources=.'
    #- '-Dsonar.qualitygate.wait=true'
  - name: 'gcr.io/clean-mountain-395906/ubuntu'
    args:
    - 'sudo apt install nodejs'
    - 'sudo apt install npm'
    - 'npm install snyk@latest -g'
  

