steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clean-mountain-395906/nodejproject', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/clean-mountain-395906/nodejproject]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'testservice-1', '--nodejproject, 'gcr.io/clean-mountain-395906/nodejproject, '--region', 'us-central1']
images:
- gcr.io/clean-mountain-395906/nodejproject
