steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app-name', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-app-name']

  # Run SonarCloud analysis
  - name: 'gcr.io/sonarqube-scan'
    args: [
      '-Dsonar.organization=cleanmoutain \ ',
      '-Dsonar.projectKey=cleanmoutain_cleane \',
      '-Dsonar.sources=. \',
      '-Dsonar.host.url=https://sonarcloud.io',
      '-Dsonar.login=$_SONAR_TOKEN',
    ]
