steps:
   # Install Node.js
  - name: 'node:14'
    entrypoint: npm
    args: ['install']

  # Run SonarCloud analysis
  - name: 'gcr.io/sonarqube-scan'
    entrypoint: 'sonar-scanner'
  
    args: [
      '-Dsonar.organization=cleanmoutain \ ',
      '-Dsonar.projectKey=cleanmoutain_cleane \',
      '-Dsonar.sources=. \',
      '-Dsonar.host.url=https://sonarcloud.io',
      '-Dsonar.login=${_SONAR_TOKEN}',
    ]
    id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline


  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/clean-mountain-395906/cloudsonarscner', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/clean-mountain-395906/cloudsonarscner']


images:
- 'gcr.io/clean-mountain-395906/cloudsonarscner'
