
 steps:
 - name: 'node'
   entrypoint: 'npm'
   args: ['install', '-g', 'snyk']
 - name: 'node'
   args: ['-v','snyk', 'auth', '$_SNYK_TOKEN']
    
 - name: 'node'
   args: ['snyk', 'test']


            

  

